grep -oh "p-value: [0-9.e-]*" test.output/1.prot.sowh.t1/sowh.info.test* >analysis.output/stats_output/1.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/2.prot.sowhat.t1/sowh.info.test* >analysis.output/stats_output/2.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/4.prot.sowhat.t2/sowh.info.test* >analysis.output/stats_output/3.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/3.prot.sowh.t2/sowh.info.test* >analysis.output/stats_output/4.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/5.prot.sowh.pb.t2/sowh.info.test* >analysis.output/stats_output/5.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/6.prot.sowhat.pb.t2/sowh.info.test* >analysis.output/stats_output/6.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/7.sullivan.sowh.t1/sowh.info.test* >analysis.output/stats_output/7.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/8.sullivan.sowhat.t1/sowh.info.test* >analysis.output/stats_output/8.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/9.sullivan.sowh.t2/sowh.info.test* >analysis.output/stats_output/9.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/10.sullivan.sowhat.t2/sowh.info.test* >analysis.output/stats_output/10.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/11.sullivan.pb.sowh.t2/sowh.info.test* >analysis.output/stats_output/11.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/12.sullivan.pb.sowhat.t2/sowh.info.test* >analysis.output/stats_output/12.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/13.castoe.sowh.t1/sowh.info.test* >analysis.output/stats_output/13.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/14.castoe.sowhat.t1/sowh.info.test* >analysis.output/stats_output/14.pvals;

cp test.output/1.prot.sowh.t1/variance.png analysis.output/stats_output/1.var.png;
cp test.output/2.prot.sowhat.t1/variance.png analysis.output/stats_output/2.var.png;
cp test.output/4.prot.sowhat.t2/variance.png analysis.output/stats_output/3.var.png;
cp test.output/3.prot.sowh.t2/variance.png analysis.output/stats_output/4.var.png;
cp test.output/5.prot.sowh.pb.t2/variance.png analysis.output/stats_output/5.var.png;
cp test.output/6.prot.sowhat.pb.t2/variance.png analysis.output/stats_output/6.var.png;
cp test.output/7.sullivan.sowh.t1/variance.png analysis.output/stats_output/7.var.png;
cp test.output/8.sullivan.sowhat.t1/variance.png analysis.output/stats_output/8.var.png;
cp test.output/9.sullivan.sowh.t2/variance.png analysis.output/stats_output/9.var.png;
cp test.output/10.sullivan.sowhat.t2/variance.png analysis.output/stats_output/10.var.png;
cp test.output/11.sullivan.pb.sowh.t2/variance.png analysis.output/stats_output/11.var.png;
cp test.output/12.sullivan.pb.sowhat.t2/variance.png analysis.output/stats_output/12.var.png;
cp test.output/13.castoe.sowh.t1/variance.png analysis.output/stats_output/13.var.png;
cp test.output/14.castoe.sowhat.t1/variance.png analysis.output/stats_output/14.var.png;
