grep -oh "p-value: [0-9.e-]*" test.output/1.protein.t1/sowh.info.test* >analysis.output/stats_output/1.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/2.protein.t1/sowh.info.test* >analysis.output/stats_output/2.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/3.sullivan.t1/sowh.info.test* >analysis.output/stats_output/3.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/4.sullivan.t1/sowh.info.test* >analysis.output/stats_output/4.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/5.sullivan.t2/sowh.info.test* >analysis.output/stats_output/5.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/6.sullivan.t2/sowh.info.test* >analysis.output/stats_output/6.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/9.protein.t2/sowh.info.test* >analysis.output/stats_output/9.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/10.protein.t2/sowh.info.test* >analysis.output/stats_output/10.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/11.sullivan.t2/sowh.info.test* >analysis.output/stats_output/11.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/13.sullivan.t2/sowh.info.test* >analysis.output/stats_output/13.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/12.hox.ax1a.jtt/sowh.info.test* >analysis.output/stats_output/12.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/14.hox.jtt.lg/sowh.info.test* >analysis.output/stats_output/14.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/15.hox.jtt.lg/sowh.info.test* >analysis.output/stats_output/15.pvals;
grep -oh "p-value: [0-9.e-]*" test.output/16.hox.jtt.lg/sowh.info.test* >analysis.output/stats_output/16.pvals;

cp test.output/1.protein.t1/variance.png analysis.output/stats_output/1.var.png;
cp test.output/2.protein.t1/variance.png analysis.output/stats_output/2.var.png;
cp test.output/3.sullivan.t1/variance.png analysis.output/stats_output/3.var.png;
cp test.output/4.sullivan.t1/variance.png analysis.output/stats_output/4.var.png;
cp test.output/5.sullivan.t2/variance.png analysis.output/stats_output/5.var.png;
cp test.output/6.sullivan.t2/variance.png analysis.output/stats_output/6.var.png;
cp test.output/9.protein.t2/variance.png analysis.output/stats_output/9.var.png;
cp test.output/10.protein.t2/variance.png analysis.output/stats_output/10.var.png;
cp test.output/11.sullivan.t2/variance.png analysis.output/stats_output/11.var.png;
cp test.output/12.hox.ax1a.jtt/variance.png analysis.output/stats_output/12.var.png;
cp test.output/13.sullivan.t2/variance.png analysis.output/stats_output/13.var.png;
cp test.output/14.hox.jtt.lg/variance.png analysis.output/stats_output/14.var.png;
cp test.output/15.hox.ax1a.jtt/variance.png analysis.output/stats_output/15.var.png;
cp test.output/16.hox.jtt.lg/variance.png analysis.output/stats_output/16.var.png;
