args=(commandArgs(TRUE))
pvals<-read.table(paste(args,".pvals",sep=""))
meanval<-mean(pvals$V2)
rangeval<-range(pvals$V2)
sorted<-sort(pvals$V2)
write(sorted,file=paste(args,".sorted",sep=""),1)
write(meanval,file=paste(args,".mean",sep=""),1)
write(rangeval,file=paste(args,".range",sep=""),1)
histname=paste(args,"hist.eps",sep="")
postscript(histname,horizontal = FALSE, onefile = FALSE, paper = "special",width=4.0,height=4.0)
par(mar=c(5,4,4,2)+0.1)
hist(pvals$V2,col="red",xlab="P-value",main="Distribution of P-values",xlim=c(0,1),breaks=seq(0,1,by=0.05))
axis(1,at=seq(0,1,by=0.1))
dev.off()
